# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naba < Formula
  desc "AI image generation CLI powered by Google Gemini"
  homepage "https://github.com/dixson3/naba"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dixson3/naba/releases/download/v0.1.0/naba_darwin_amd64.tar.gz"
      sha256 "d75bb1d912fbc5a8fc5d1e7153bf9713b8da046bfbc5a78e4d1ba4718078757b"

      def install
        bin.install "naba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dixson3/naba/releases/download/v0.1.0/naba_darwin_arm64.tar.gz"
      sha256 "49140156d74cd9b0c5d09c2c08d9a18c635bfcad66fd155eab0293c5178581c3"

      def install
        bin.install "naba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dixson3/naba/releases/download/v0.1.0/naba_linux_amd64.tar.gz"
      sha256 "5c8116a10512bc6aed95d251235dc70fe2bb4ba52d6d2e9adafb68af2c87f14d"
      def install
        bin.install "naba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dixson3/naba/releases/download/v0.1.0/naba_linux_arm64.tar.gz"
      sha256 "1342911ef08ff33e5a9ae1eb7bd7e12f775ba535c1b4f8f2ed776618e493561b"
      def install
        bin.install "naba"
      end
    end
  end

  test do
    system "#{bin}/naba", "version"
  end
end
