# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naba < Formula
  desc "AI image generation CLI powered by Google Gemini"
  homepage "https://github.com/dixson3/naba"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dixson3/naba/releases/download/v0.1.1/naba_darwin_amd64.tar.gz"
      sha256 "ceee67b4b26d35cae08ed74eda5d224b61a68ada3935d2a2c9b7a98190f482af"

      def install
        bin.install "naba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dixson3/naba/releases/download/v0.1.1/naba_darwin_arm64.tar.gz"
      sha256 "7d825dec68ff9fb34deca8edcfc88a801f77e60cff46176e945295da3dbd9d91"

      def install
        bin.install "naba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dixson3/naba/releases/download/v0.1.1/naba_linux_amd64.tar.gz"
      sha256 "f143d6d00a0a18e6502cd9d7bb241eaef589b2cc1711db377c5742816ca9c21c"
      def install
        bin.install "naba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dixson3/naba/releases/download/v0.1.1/naba_linux_arm64.tar.gz"
      sha256 "bbf1572f6f82dd653b7f1dc5128562a6301a1494072906222bb90b830c31b67f"
      def install
        bin.install "naba"
      end
    end
  end

  test do
    system "#{bin}/naba", "version"
  end
end
